/* All 38 exercises: id, name, pivot, page, one-line gist (for cards) */
const PIVOTS = {
  defusion:   { name: 'Defusion',   ru: 'Разделение', emoji: '🐕', color: '#7A4BA0', href: 'defusion.html',   total: 11 },
  self:       { name: 'Self',       ru: 'Самость',    emoji: '👁️', color: '#2589C9', href: 'self.html',       total: 7 },
  acceptance: { name: 'Acceptance', ru: 'Принятие',   emoji: '🌊', color: '#3E8E5A', href: 'acceptance.html', total: 4 },
  presence:   { name: 'Presence',   ru: 'Присутствие', emoji: '⚓', color: '#C08A17', href: 'presence.html',  total: 6 },
  values:     { name: 'Values',     ru: 'Ценности',   emoji: '🌟', color: '#D25B4A', href: 'values.html',     total: 5 },
  action:     { name: 'Action',     ru: 'Действие',   emoji: '👣', color: '#2E7D74', href: 'action.html',     total: 5 }
};

const EXERCISES = [
  { id:'d1', pivot:'defusion', name:'Disobey on purpose', gist:'Walk around the room while repeating out loud "I cannot walk around this room". Five reps. The mind\'s power over your legs is a bluff; call it.' },
  { id:'d2', pivot:'defusion', name:'Name your mind', gist:'Give your mind a name and greet it politely. A named mind is a separate voice you can listen to without obeying.' },
  { id:'d3', pivot:'defusion', name:'Thank your mind', gist:'When the chatter starts: "Thanks for that thought, really. I see you\'re trying to help. I\'ve got this." Sincerely, no sarcasm.' },
  { id:'d4', pivot:'defusion', name:'Sing it', gist:'Take the sticky thought and sing it to Happy Birthday. Fast, slow, different tunes. The thought stays; its grip doesn\'t.' },
  { id:'d5', pivot:'defusion', name:'Say it backwards', gist:'Find the loaded word inside the thought and say it reversed. "Stupid" is also "diputs". You are looking AT a thought.' },
  { id:'d6', pivot:'defusion', name:'See it as an object', gist:'Give the thought a size, shape, color, speed, texture. Then do the same to your reaction to it. Then look at the original again.' },
  { id:'d7', pivot:'defusion', name:'Funny voices', gist:'Say the hard thought in a cartoon voice. Rule: mock the delivery, never yourself.' },
  { id:'d8', pivot:'defusion', name:'The hand exercise', gist:'Thought written on your palm: on your face you see nothing else; at arm\'s length you see the room; off to the side you can act. Where is your hand right now?' },
  { id:'d9', pivot:'defusion', name:'Carry it with you', gist:'Write the thought on paper, honor it as a page of your history, and carry it in your pocket. Pat it now and then.' },
  { id:'d10', pivot:'defusion', name:'The small child', gist:'Hear the old painful thought in the voice of you as a small child. Then care for that child. Then do the equivalent for yourself.' },
  { id:'d11', pivot:'defusion', name:'Social sharing', gist:'Advanced: wear the self-judgment openly (a badge, a shirt) as a declaration that it no longer runs your life. Only after the inner work.' },
  { id:'s1', pivot:'self', name:'I am / I am not', gist:'Write "I am ___" ×3, add "...or maybe not", cross the content out, then re-situate each: "When [situation] and I [behavior], I feel ___".' },
  { id:'s2', pivot:'self', name:'Rewrite your story', gist:'Write 200 words on a struggle. Circle reactions, underline facts. Rewrite with a totally different meaning using every circled and underlined piece.' },
  { id:'s3', pivot:'self', name:'One honest conversation', gist:'In your next talk, watch the micro-pulls to embellish. Catch them with compassion and say the truer thing.' },
  { id:'s4', pivot:'self', name:'Catch the noticer', gist:'Every time you touch your phone or keys, ask: who is noticing this right now? One second of the observing "I".' },
  { id:'s5', pivot:'self', name:'Awareness vs contents', gist:'"I am aware of X. I am not X. My awareness contains X." Five minutes, any X.' },
  { id:'s6', pivot:'self', name:'Waiting for a meeting', gist:'Before a hard meeting: who watches you wait? Then step into the other person\'s view: what do they feel, fear, care about? Can you both win?' },
  { id:'s7', pivot:'self', name:'Perspective for acceptance', gist:'Contact the pain, float out of your body, view yourself across the room, then advise yourself from ten years wiser. Write the memo.' },
  { id:'a1', pivot:'acceptance', name:'Say yes', gist:'Scan the room through "no" for two minutes, then through "yes". Add posture: closed for no, open for yes. Then run it on a feeling.' },
  { id:'a2', pivot:'acceptance', name:'The caring exercise', gist:'Hold the hard feeling like a fragile flower, a crying child, a glass of cold water. One full minute. It works even when the mind says it can\'t.' },
  { id:'a3', pivot:'acceptance', name:'Widen the view', gist:'One painful experience, eleven slow questions: the sensation, the thought, the family echo, the lesson, the value hiding inside it.' },
  { id:'a4', pivot:'acceptance', name:'Practice the opposite', gist:'Ask where the mind says you cannot go. Go there, by choice, playfully. Reclaim the territory.' },
  { id:'p1', pivot:'presence', name:'Simple meditation', gist:'Sit, soft gaze down, rest on the breath. Every drift you catch and return is one rep for the attention muscle.' },
  { id:'p2', pivot:'presence', name:'Feet, then both feet', gist:'Two minutes on the left foot, two on the right, two holding both at once. Grounding that works mid-conversation and can\'t trigger breath-panic.' },
  { id:'p3', pivot:'presence', name:'Widen and narrow with music', gist:'Multi-instrument track. Whole band, then just the bass, then the drums, then the band again. You steer, not the music.' },
  { id:'p4', pivot:'presence', name:'Open your focus', gist:'Focus on objects one by one, then on the space between all of them. Sharp beam, wide beam. Try it in your next meeting.' },
  { id:'p5', pivot:'presence', name:'Present via the past', gist:'"Right now I am remembering that..." then label each arrival: "Right now I am having the emotion of..." The reaction is always happening now.' },
  { id:'p6', pivot:'presence', name:'Inside / Outside', gist:'While doing chores, keep one channel on the task and one on a body sensation. Shift between them without dropping either.' },
  { id:'v1', pivot:'values', name:'Values writing', gist:'Ten minutes of nonstop writing about one value that matters. Then underline the actions and circle the qualities. This fuels everything.' },
  { id:'v2', pivot:'values', name:'Draw the sweetness', gist:'Relive one genuinely sweet moment, then draw what it says about how you want to live. No words on the drawing. Pin it where you\'ll see it.' },
  { id:'v3', pivot:'values', name:'Pain into purpose', gist:'List the barriers, then flip each: what would I have to stop caring about for this to stop hurting? Write the reminder sentence.' },
  { id:'v4', pivot:'values', name:'Write your next chapter', gist:'If next year were the defining chapter of your book, what would its theme be? Ten minutes on who you hope to become.' },
  { id:'v5', pivot:'values', name:'I have a secret', gist:'Do one values-based good deed in total secrecy, forever. If keeping the secret is hard, that itself is the finding.' },
  { id:'c1', pivot:'action', name:'Small steps', gist:'Pick the smallest reliable step toward the behavior. If it wobbles, shrink it. Size doesn\'t matter; the pattern does.' },
  { id:'c2', pivot:'action', name:'Habits inside routines', gist:'Attach the new behavior to an existing daily anchor: the apple with the first sip of coffee. Pairing beats swapping.' },
  { id:'c3', pivot:'action', name:'Reverse-compass habits', gist:'When the mind commands avoidance, do a small deliberate opposite. A few reps and the command loses its force.' },
  { id:'c4', pivot:'action', name:'"Because I choose to"', gist:'Always keep one hard commitment running for no reason at all. It starves guilt-motivation and builds trust in your own word.' },
  { id:'c5', pivot:'action', name:'No one is an island', gist:'Share the commitment with witnesses who know the pivots, as an exchange of care, and let them flag you gently when you\'re hooked.' }
];
